"""set __tablename__ split-based

Revision ID: 858165ec030f
Revises: 68a7bf496833
Create Date: 2026-05-26 23:44:40.257749

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '858165ec030f'
down_revision: Union[str, Sequence[str], None] = '68a7bf496833'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
        # Perform safe table renames to preserve data and constraints.
        op.rename_table('pendingregistration', 'pending_registration')
        op.rename_table('refreshtoken', 'refresh_token')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
        # Reverse the renames
        op.rename_table('pending_registration', 'pendingregistration')
        op.rename_table('refresh_token', 'refreshtoken')
    # ### end Alembic commands ###
